In [2]:
import numpy as np

The Basics


In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

In [ ]:
a.ndim

In [ ]:
b.shape

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
a.nbytes

In [ ]:
a.size

Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

In [ ]:
a[1, 5]

In [ ]:
a[0, :]

In [ ]:
a[:, 2]

In [ ]:
a[0, 1:-1:2]

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

In [ ]:
b[0,1,1]

In [ ]:
b[:,1,:] = [[9,9,9],[8,8]]

In [ ]:
b

Initializing Different Types of Arrays

In [ ]:
np.zeros((2,3))

In [ ]:
np.ones((4,2,2), dtype='int32')

In [ ]:
np.full((2,2), 99)

In [ ]:
np.full_like(a, 4)

In [ ]:
np.random.rand(4,2)

In [ ]:
np.random.randint(-4,8, size=(3,3))

In [ ]:
np.identity(5)

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

Mathematics


In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
np.cos(a)

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
c = np.identity(3)
np.linalg.det(c)

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.sum(stats, axis=0)

Reorganizing Arrays


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3)) 
print(after)

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

Miscellaneous


In [17]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [18]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])